### ISSUE TITLE
Swift Module: is not a recognized Objective-C method return promise

### ISSUE THREAD

**Issue by paulcapelo** [brodybits/react-native-module-init#50]
Hi i hope you can help me i try to create a module with swift method but it response error

i try of differents way and nothing  
```
Error
getTOTP:tiempo:fecha:resolver:rejecter: is not a recognized Objective-C method.' was thrown while invoking getTOTP on target RNTotplibe with params (
    2502,
    2503
)
```

```
.swift
  import Foundation
@objc(RNTotplibe)
class RNTotplibe: NSObject {
    @objc(getTOTP:tiempo:fecha:resolve:reject:)
    func getTOTP(semilla: String, tiempo: String, fecha: String, resolve: RCTPromiseResolveBlock, reject: RCTPromiseRejectBlock) -> Void {
 // let valor = generateTOTP(semilla, movingFactor: counter, codeDigits: 6)
         resolve(["yfytfvtyytyyff"]);
    }
}
```

```
.m
#import <React/RCTBridgeModule.h>
#import <CommonCrypto/CommonHMAC.h>

@interface RCT_EXTERN_MODULE(RNTotplibe, NSObject)
// RCT_EXTERN_METHOD(getTOTP:(NSString *)semilla tiempo:(NSString *)tiempo fecha:(NSString *)fecha resolver:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject );
RCT_EXTERN_METHOD(getTOTP);
```

``` 
.h
#import <React/RCTBridgeModule.h>
#import <CommonCrypto/CommonHMAC.h>
```

[https://github.com/paulcapelo/simpleTotp.git](url)
thanks for your coments

**Comment by brodybits** [comment]
I think this is something that should be fixed on create-react-native-module that this utility depends on. There seem to be some solutions already discussed in <https://github.com/brodybits/create-react-native-module/issues/221>.

**Comment by paulcapelo** [comment]
yeah i does each step but not working still return error maybe you have a example thanks

**Comment by brodybits** [comment]
I would like to keep discussion in <https://github.com/brodybits/create-react-native-module/issues/221>, which is now pinned with the **help wanted** label. I personally do not work with Swift, best to get help from others in the user community. Thanks.
